stages:
  - triggers

run_go_ci:
  stage: triggers
  trigger:
    include: .gitlab/go-ci.yml
    strategy: depend

run_ts_ci:
  stage: triggers
  trigger:
    include: .gitlab/ts-ci.yml
    strategy: depend
