stages:
  - triggers

run_go_ci:
  stage: triggers
  trigger:
    include: .gitlab/go-ci.yml
    strategy: depend
# TODO: should be comment until add a ts package
# run_ts_ci:
#   stage: triggers
#   trigger:
#     include: .gitlab/ts-ci.yml
