image: node:20.11.0

stages:
  - installation
  - build
  - type_check
  - lint
  - test
  - coverage
  - changeset

installation:
  stage: installation
  cache:
    key: ${CI_COMMIT_REF_NAME}-ts
    policy: push
    paths:
      - node_modules
      - '**/node_modules'
  script:
    - npm ci

build:
  stage: build
  needs: ['installation']
  cache:
    - key: ${CI_COMMIT_REF_NAME}-ts
      policy: pull-push
      paths:
        - node_modules
        - '**/node_modules'
        - '**/dist'
  script:
    - npm run build --workspace packages


type_check:
  stage: type_check
  needs: ['build']
  cache:
    key: ${CI_COMMIT_REF_NAME}-ts
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run type-check --workspace packages
    - npm run type-check --workspace services/keygen-service

lint:
  stage: lint
  needs: ['type_check']
  cache:
    key: ${CI_COMMIT_REF_NAME}-ts
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run lint --workspace packages
    - npm run lint --workspace services/keygen-service

test:
  stage: test
  needs: ['lint']
  cache:
    key: ${CI_COMMIT_REF_NAME}-ts
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run test --workspace packages

coverage:
  stage: coverage
  needs: ['test']
  cache:
    key: ${CI_COMMIT_REF_NAME}-ts
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run coverage --workspace packages
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: '**/coverage/cobertura-coverage.xml'

changeset:
  stage: changeset
  cache:
    key: ${CI_COMMIT_REF_NAME}-ts
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  before_script:
    - git fetch origin dev
  script:
    - npx changeset status --since=origin/dev
