name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build tss-api
    permissions: write-all
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go: [1.18.0]
        include:
          - os: macos-latest
            platform: macOS
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GoLang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run build
        run: |
          go version
          CGO_ENABLED=0 go build -trimpath -o bin/rosenTss-${{ matrix.platform }}-${{ github.ref_name }}
          mkdir conf
          mv conf.env.sample conf/conf.env

      - name: Prepare Release File
        uses: vimtor/action-zip@v1
        with:
          files: conf/ ./bin/rosenTss-${{ matrix.platform }}-${{ github.ref_name }}
          dest: rosenTss-${{ matrix.platform }}-${{ github.ref_name }}.zip

      - name: Upload Release File
        uses: softprops/action-gh-release@v1
        with:
          files: ./rosenTss*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
